os: linux
sudo: required
dist: trusty
language: c

compiler:
  - clang

branches:
  only:
    - coverity

before_install:
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libssl-dev
  - wget https://red.libssh.org/attachments/download/121/libssh-0.6.5.tar.xz
  - tar -xJf libssh-0.6.5.tar.xz
  - mkdir libssh-0.6.5/build && cd libssh-0.6.5/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJf cmocka-1.0.1.tar.xz
  - mkdir cmocka-1.0.1/build && cd cmocka-1.0.1/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - git clone https://github.com/CESNET/libyang.git
  - mkdir libyang/build && cd libyang/build
  - git checkout devel
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "Iqj+Zdu6+oIi/ERwJreofwiyQ9zwTqME68AyNX6nNTGmiAq+LQM8XMqoyKdfCpm8Ui9BQs1qGgvEQhY2ZRW+Ko9d5ervr3ZEpbXilEoog1HD4ZgZ/Vt9eldOkA6PWD/xKFNvZvtwxfdpBXAYveycvT76z0FKBuq9lAFo032QvY5bhbjQR5sN2sP80fIyQHGls9sOpuElMAgP4h5Oys83PkOD+kqG6UVn7zW2xi8AwWhFlFUXMdusXzsTTwbbqG6aV+7BQC74GyJsKUz3Zk+g0mMerNqs7ihzkKC3QHRsDRjg+X4E5EchQtsTsbw9+pu13cALj+PFNixOg4r9MMf0LXNohMWvBw59Lg9ppF8E6VKoMF5Rqz6kPgyIPbZGPxVIuEvdP+V8k5qYYQM70cM/11hx3k0x7EDQ1b68FgnYdZjhh1oBGQJZGvBWMc0hS3uJ7eEZeSbcvpxMLze7+XapAVDZE3lXOveeAFe+KRCSvjGcpMhDzXPZGZhJSFmLYZ+tMgPAPSvHfHmVotNESr8NoEdr6kURPJKviQTUF/ZoXAMcOhezDm/Xn478atZ8B+VSyLRdSUuuHvT98USgGTaAttmfPxxncmVEkdJW6bYICZKXADKKrPHes7joREWXKvgbOe8n5glGKoWR2xz1EXCtkCQi9jdtYHfPl9Ll+RK3yGM="

addons:
  coverity_scan:
    project:
      name: "CESNET/libnetconf2"
    notification_email: rkrejci@cesnet.cz
    build_command_prepend: "mkdir build ; cd build ; cmake -DENABLE_TLS=ON -DENABLE_SSH=ON .. "
    build_command: "make"
    branch_pattern: coverity

script:
  # do nothing, everything here is done in coverity addon
  - true

